import { useEffect, useState } from "react";
import { ArrowLeft, ArrowRight, Send } from "lucide-react";
import { Link, useParams } from "wouter";
import { BackToTopButton } from "../components/BackToTopButton";
import { LOCALE_OPTIONS, translations, type Locale } from "../i18n";
import { FACEBOOK_LINK, optimizedAsset } from "@shared/morningGreen";
import { CATALOG_STORAGE, CATALOG_VOLUME, ENGLISH_PRODUCT_NAMES, getProductBySlug, localizedCategory, localizedDescriptor, localizedProductDetail, localizedProductName, MENU_PRODUCTS, tasteDescriptionForProduct, priceForProduct } from "../lib/morningGreenCatalog";

type DetailParams = { productSlug: string };

function LocaleSwitcher({ locale, onChange, label }: { locale: Locale; onChange: (next: Locale) => void; label: string }) {
  const labels: Record<Locale, string> = { vi: "Tiếng Việt", en: "English", zh: "Tiếng Trung" };
  return <div className="flex items-center gap-2 text-[12px] font-medium tracking-[0.06em] text-[#1f3b2c]" aria-label={label}>{LOCALE_OPTIONS.map((option, index) => <span key={option.id} className="flex items-center gap-2">{index > 0 && <span className="text-[#ad8e50]/50">·</span>}<button type="button" aria-label={labels[option.id]} aria-pressed={locale === option.id} onClick={() => onChange(option.id)} className={`transition hover:text-[#ad8e50] ${locale === option.id ? "text-[#ad8e50] underline underline-offset-4" : "opacity-65"}`}>{option.label}</button></span>)}</div>;
}

export default function ProductDetail() {
  const { productSlug = "" } = useParams<DetailParams>();
  const [locale, setLocale] = useState<Locale>(() => { const saved = window.localStorage.getItem("morning-green-locale"); return saved === "en" || saved === "zh" ? saved : "vi"; });
  const copy = translations[locale];
  useEffect(() => { window.localStorage.setItem("morning-green-locale", locale); document.documentElement.lang = locale === "zh" ? "zh-CN" : locale; document.title = copy.meta.title; document.querySelector('meta[name="description"]')?.setAttribute("content", copy.meta.description); }, [locale, copy]);
  useEffect(() => { window.scrollTo({ top: 0, left: 0, behavior: "auto" }); }, [productSlug]);
  const product = getProductBySlug(productSlug);
  if (!product) return <main className="min-h-screen bg-[#f5f1e7] px-5 py-12 text-[#1f3b2c]"><Link href="/shop" className="text-sm underline underline-offset-4">{copy.productDetail.backToShop}</Link><p className="mt-12 font-serif text-4xl">{copy.menu.noResults}</p></main>;
  const productIndex = MENU_PRODUCTS.findIndex((item) => item.code === product.code);
  const previous = MENU_PRODUCTS[(productIndex - 1 + MENU_PRODUCTS.length) % MENU_PRODUCTS.length];
  const next = MENU_PRODUCTS[(productIndex + 1) % MENU_PRODUCTS.length];
  const tasteSummary = locale === "vi" ? tasteDescriptionForProduct(product) : localizedProductDetail(product, locale);
  const idealFor = copy.menu.fitNote;
  const ingredientLine = localizedDescriptor(product.ingredients, locale);

  return <main className="product-detail-page min-h-screen bg-[#f5f1e7] text-[#1f3b2c]">
    <header className="product-detail-header border-b border-[#1f3b2c]/10 px-5 py-4 sm:px-8 lg:px-12"><div className="mx-auto flex max-w-7xl items-center justify-between gap-5"><Link href="/shop" className="inline-flex items-center gap-2 text-[11px] font-semibold uppercase tracking-[0.16em] text-[#1f3b2c] transition hover:text-[#ad8e50]"><ArrowLeft size={14} /> {copy.productDetail.backToShop.replace("← ", "")}</Link><LocaleSwitcher locale={locale} onChange={setLocale} label={copy.ui.languageSelector} /></div></header>
    <section className="mx-auto grid max-w-7xl gap-12 px-5 pb-20 pt-8 sm:px-8 lg:grid-cols-[1.06fr_0.94fr] lg:gap-20 lg:px-12 lg:pb-28 lg:pt-14">
      <div className="product-detail-hero-image relative flex min-h-[56vh] items-center justify-center overflow-hidden bg-[#e8ead9] px-6 py-8 lg:min-h-[70vh]"><div className="product-detail-ambient" /><div className="product-detail-geometry product-detail-geometry-one" /><div className="product-detail-geometry product-detail-geometry-two" /><nav className="pointer-events-none absolute inset-x-4 top-1/2 z-30 flex -translate-y-1/2 items-center justify-between sm:inset-x-6" aria-label={copy.productDetail.navigationAria}><Link href={`/shop/${previous.code.toLowerCase()}`} aria-label={`${copy.productDetail.previous}: ${localizedProductName(previous, locale)}`} title={`${copy.productDetail.previous}: ${localizedProductName(previous, locale)}`} className="pointer-events-auto grid h-11 w-11 place-items-center rounded-full border border-[#1f3b2c]/15 bg-[#f5f1e7]/90 text-[#1f3b2c] shadow-[0_8px_18px_rgba(23,53,39,0.12)] backdrop-blur-sm transition duration-200 hover:border-[#ad8e50] hover:bg-[#f5f1e7] hover:text-[#ad8e50] focus:outline-none focus-visible:ring-2 focus-visible:ring-[#ad8e50] focus-visible:ring-offset-2 sm:h-12 sm:w-12"><ArrowLeft size={17} strokeWidth={1.6} /></Link><Link href={`/shop/${next.code.toLowerCase()}`} aria-label={`${copy.productDetail.next}: ${localizedProductName(next, locale)}`} title={`${copy.productDetail.next}: ${localizedProductName(next, locale)}`} className="pointer-events-auto grid h-11 w-11 place-items-center rounded-full border border-[#1f3b2c]/15 bg-[#f5f1e7]/90 text-[#1f3b2c] shadow-[0_8px_18px_rgba(23,53,39,0.12)] backdrop-blur-sm transition duration-200 hover:border-[#ad8e50] hover:bg-[#f5f1e7] hover:text-[#ad8e50] focus:outline-none focus-visible:ring-2 focus-visible:ring-[#ad8e50] focus-visible:ring-offset-2 sm:h-12 sm:w-12"><ArrowRight size={17} strokeWidth={1.6} /></Link></nav><img src={optimizedAsset(product.image)} alt={`${localizedProductName(product, locale)} — Morning Green`} decoding="async" fetchPriority="high" className="product-detail-hero-bottle relative z-10 h-[58vh] max-h-[690px] w-full max-w-[430px] object-contain object-center drop-shadow-[0_28px_22px_rgba(5,36,25,0.18)]" style={{ transform: `scale(${product.scale})` }} /></div>
      <div className="min-w-0 flex flex-col justify-center lg:py-12"><p className="product-detail-reveal text-[10px] font-semibold uppercase tracking-[0.28em] text-[#ad8e50]">{localizedCategory(product.category, locale)}</p><h1 className="product-detail-reveal mt-4 w-full max-w-none whitespace-nowrap font-serif text-[clamp(1.8rem,3.6vw,4rem)] font-normal leading-[1.04] tracking-[-0.04em]">{localizedProductName(product, locale)}</h1><p className="product-detail-reveal mt-3 text-[15px] font-medium text-[#526151]">{locale === "vi" ? ENGLISH_PRODUCT_NAMES[product.code] : product.name}</p><p className="product-detail-reveal mt-4 text-[17px] font-semibold text-[#1f3b2c]">{copy.menu.price}: {priceForProduct(product)}</p><p className="product-detail-reveal mt-7 max-w-xl text-[16px] leading-8 text-[#5f6d5e]">{localizedProductDetail(product, locale)}</p><p className="product-detail-reveal mt-5 text-[10px] font-semibold uppercase tracking-[0.24em] text-[#ad8e50]">{copy.menu.tasteNotes.join(" · ")}</p>
        <div className="mt-12"><section className="product-detail-section-reveal grid grid-cols-[44px_1fr] gap-4 border-t border-[#1f3b2c]/14 py-6"><span className="font-serif text-3xl text-[#ad8e50]/75">01</span><div><h2 className="text-[10px] font-semibold uppercase tracking-[0.22em] text-[#697363]">{copy.productDetail.taste}</h2><p className="mt-3 max-w-lg text-[14px] leading-7 text-[#5f6d5e]">{tasteSummary}</p></div></section><section className="product-detail-section-reveal grid grid-cols-[44px_1fr] gap-4 border-t border-[#1f3b2c]/14 py-6"><span className="font-serif text-3xl text-[#ad8e50]/75">02</span><div><h2 className="text-[10px] font-semibold uppercase tracking-[0.22em] text-[#697363]">{copy.productDetail.ingredients}</h2><p className="mt-3 text-[14px] leading-7 text-[#5f6d5e]">{ingredientLine}</p></div></section><section className="product-detail-section-reveal grid grid-cols-[44px_1fr] gap-4 border-y border-[#1f3b2c]/14 py-6"><span className="font-serif text-3xl text-[#ad8e50]/75">03</span><div><h2 className="text-[10px] font-semibold uppercase tracking-[0.22em] text-[#697363]">{copy.productDetail.information}</h2><dl className="mt-3 grid max-w-lg gap-2 text-[13px] leading-6 text-[#5f6d5e] sm:grid-cols-3"><div><dt className="text-[9px] font-semibold uppercase tracking-[0.16em] text-[#8a9587]">{copy.productDetail.volume}</dt><dd>{CATALOG_VOLUME}</dd></div><div><dt className="text-[9px] font-semibold uppercase tracking-[0.16em] text-[#8a9587]">{copy.productDetail.storage}</dt><dd>{CATALOG_STORAGE}</dd></div><div><dt className="text-[9px] font-semibold uppercase tracking-[0.16em] text-[#8a9587]">{copy.productDetail.type}</dt><dd>{localizedCategory(product.category, locale)}</dd></div></dl></div></section><section className="product-detail-section-reveal mt-10"><h2 className="text-[10px] font-semibold uppercase tracking-[0.22em] text-[#697363]">{copy.productDetail.idealFor}</h2><p className="mt-3 max-w-lg text-[14px] leading-7 text-[#5f6d5e]">{idealFor}</p></section><a href={FACEBOOK_LINK} target="_blank" rel="noreferrer" className="mt-10 inline-flex w-fit items-center gap-2 rounded-full bg-[#1f3b2c] px-5 py-3 text-[12px] font-semibold text-[#f5f1e7] transition hover:-translate-y-0.5 hover:bg-[#162c20] focus:outline-none focus-visible:ring-2 focus:ring-[#ad8e50] focus-visible:ring-offset-2"><Send size={15} strokeWidth={1.6} />{copy.action.facebookAdvice}</a></div>
      </div>
    </section>
    <nav className="mx-auto flex max-w-7xl items-stretch justify-between border-t border-[#1f3b2c]/14 px-5 py-8 sm:px-8 lg:px-12" aria-label={copy.productDetail.navigationAria}><Link href={`/shop/${previous.code.toLowerCase()}`} className="group max-w-[46%] text-left"><span className="flex items-center gap-2 text-[10px] font-semibold uppercase tracking-[0.18em] text-[#697363] transition group-hover:text-[#ad8e50]"><ArrowLeft size={14} /> {copy.productDetail.previous}</span><span className="mt-2 block font-serif text-lg text-[#1f3b2c] transition group-hover:text-[#ad8e50]">{localizedProductName(previous, locale)}</span></Link><Link href={`/shop/${next.code.toLowerCase()}`} className="group max-w-[46%] text-right"><span className="flex items-center justify-end gap-2 text-[10px] font-semibold uppercase tracking-[0.18em] text-[#697363] transition group-hover:text-[#ad8e50]">{copy.productDetail.next} <ArrowRight size={14} /></span><span className="mt-2 block font-serif text-lg text-[#1f3b2c] transition group-hover:text-[#ad8e50]">{localizedProductName(next, locale)}</span></Link>    </nav>
    <BackToTopButton label={copy.ui.backToTop} />
  </main>;
}
